# Generated by Django 6.1 on 2026-08-27 17:03

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auditevent_historicalauditevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('rule_code', models.CharField(db_index=True, help_text='Display identifier for the rule (e.g., VAL_001 or VL-0001).', max_length=50, unique=True)),
                ('strategy_key', models.CharField(blank=True, db_index=True, help_text='Explicit internal strategy handler key (e.g., MISSING_LOAN_ID, MATURITY_BEFORE_ORIGINATION).', max_length=50, null=True)),
                ('rule_name', models.CharField(help_text='Human-readable rule title (e.g., Missing Loan ID, Maturity Before Origination).', max_length=255)),
                ('field_name', models.CharField(db_index=True, help_text='Primary target loan dataset field evaluated by this rule (e.g., loan_id, current_balance).', max_length=100)),
                ('description', models.TextField(help_text='Detailed description of the validation check and business logic rule.')),
                ('severity', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=2, help_text='Default severity level assigned to exceptions flagged by this rule (Low, Medium, High, Critical).')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Toggle to dynamically enable or disable rule execution in the Validation Engine.')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text="Configurable parameter thresholds and options for the rule strategy (e.g., {'max_rate': 35.0}).", null=True)),
            ],
            options={
                'verbose_name': 'Validation Rule',
                'verbose_name_plural': 'Validation Rules',
                'ordering': ['rule_code'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalValidationRule',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('rule_code', models.CharField(db_index=True, help_text='Display identifier for the rule (e.g., VAL_001 or VL-0001).', max_length=50)),
                ('strategy_key', models.CharField(blank=True, db_index=True, help_text='Explicit internal strategy handler key (e.g., MISSING_LOAN_ID, MATURITY_BEFORE_ORIGINATION).', max_length=50, null=True)),
                ('rule_name', models.CharField(help_text='Human-readable rule title (e.g., Missing Loan ID, Maturity Before Origination).', max_length=255)),
                ('field_name', models.CharField(db_index=True, help_text='Primary target loan dataset field evaluated by this rule (e.g., loan_id, current_balance).', max_length=100)),
                ('description', models.TextField(help_text='Detailed description of the validation check and business logic rule.')),
                ('severity', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=2, help_text='Default severity level assigned to exceptions flagged by this rule (Low, Medium, High, Critical).')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Toggle to dynamically enable or disable rule execution in the Validation Engine.')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text="Configurable parameter thresholds and options for the rule strategy (e.g., {'max_rate': 35.0}).", null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Validation Rule',
                'verbose_name_plural': 'historical Validation Rules',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LoanException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('rule_code', models.CharField(db_index=True, help_text='Rule code at time of exception creation for lineage preservation.', max_length=50)),
                ('field_name', models.CharField(db_index=True, help_text='Target field name associated with the exception (e.g., current_balance).', max_length=100)),
                ('severity', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], db_index=True, default=2, help_text='Severity level assigned to this exception instance.')),
                ('description', models.TextField(help_text='Specific error message or failure explanation for this record.')),
                ('status', models.IntegerField(choices=[(1, 'Open'), (2, 'Under Review'), (3, 'Resolved (Accepted)'), (4, 'Resolved (Edited)'), (5, 'Rejected')], db_index=True, default=1, help_text='Current review status of the exception (Open, Under Review, Resolved Accepted, Resolved Edited, Rejected).')),
                ('reviewer_comment', models.TextField(blank=True, help_text='Comments or notes recorded by the Reviewer during exception handling.', null=True)),
                ('override_value', models.CharField(blank=True, help_text='Manual override value entered or accepted by the Reviewer for the flagged field.', max_length=255, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Timestamp when this exception was resolved or rejected.', null=True)),
                ('batch', models.ForeignKey(help_text='Upload batch during which this exception was flagged.', on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='app.uploadbatch')),
                ('raw_record', models.ForeignKey(help_text='Associated raw loan record that violated the validation rule.', on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='app.rawloanrecord')),
                ('resolved_by', models.ForeignKey(blank=True, help_text='Reviewer user account that resolved or rejected this exception.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_exceptions', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(blank=True, help_text='Validation rule definition that generated this exception.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exceptions', to='app.validationrule')),
            ],
            options={
                'verbose_name': 'Loan Exception',
                'verbose_name_plural': 'Loan Exceptions',
                'ordering': ['-severity', '-created'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalLoanException',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('rule_code', models.CharField(db_index=True, help_text='Rule code at time of exception creation for lineage preservation.', max_length=50)),
                ('field_name', models.CharField(db_index=True, help_text='Target field name associated with the exception (e.g., current_balance).', max_length=100)),
                ('severity', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], db_index=True, default=2, help_text='Severity level assigned to this exception instance.')),
                ('description', models.TextField(help_text='Specific error message or failure explanation for this record.')),
                ('status', models.IntegerField(choices=[(1, 'Open'), (2, 'Under Review'), (3, 'Resolved (Accepted)'), (4, 'Resolved (Edited)'), (5, 'Rejected')], db_index=True, default=1, help_text='Current review status of the exception (Open, Under Review, Resolved Accepted, Resolved Edited, Rejected).')),
                ('reviewer_comment', models.TextField(blank=True, help_text='Comments or notes recorded by the Reviewer during exception handling.', null=True)),
                ('override_value', models.CharField(blank=True, help_text='Manual override value entered or accepted by the Reviewer for the flagged field.', max_length=255, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Timestamp when this exception was resolved or rejected.', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('batch', models.ForeignKey(blank=True, db_constraint=False, help_text='Upload batch during which this exception was flagged.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.uploadbatch')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('raw_record', models.ForeignKey(blank=True, db_constraint=False, help_text='Associated raw loan record that violated the validation rule.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.rawloanrecord')),
                ('resolved_by', models.ForeignKey(blank=True, db_constraint=False, help_text='Reviewer user account that resolved or rejected this exception.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(blank=True, db_constraint=False, help_text='Validation rule definition that generated this exception.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.validationrule')),
            ],
            options={
                'verbose_name': 'historical Loan Exception',
                'verbose_name_plural': 'historical Loan Exceptions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
