# Generated by Django 6.1 on 2026-08-28 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_validationrule_historicalvalidationrule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationrule',
            name='rule_code',
            field=models.CharField(db_index=True, help_text='Display identifier for the rule (e.g., VAL_001 or VL-0001).', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='validationrule',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True)), fields=('rule_code',), name='unique_active_validation_rule_code'),
        ),
    ]
