# Generated by Django 6.1 on 2026-08-29 12:28

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_validationrule_rule_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('recommendation_type', models.IntegerField(choices=[(1, 'Exception Review'), (2, 'Rule Generation')], db_index=True, default=1, help_text='Categorical type of AI suggestion (Exception Review or Rule Generation).')),
                ('suggested_value', models.CharField(blank=True, help_text='Suggested corrected value or proposed rule code generated by AI.', max_length=255, null=True)),
                ('explanation', models.TextField(help_text='Natural language explanation of validation failure, conflict analysis, or rule rationale.')),
                ('reasoning', models.TextField(blank=True, help_text='Step-by-step logic used by the AI copilot during decision generation.', null=True)),
                ('confidence_score', models.FloatField(default=0.0, help_text='Confidence score between 0.0 and 1.0 assigned by the AI copilot.')),
                ('prompt_text', models.TextField(blank=True, help_text='Exact prompt text submitted to the LLM model for audit transparency.', null=True)),
                ('model_name', models.IntegerField(choices=[(1, 'Gemini 2.5 Flash'), (2, 'ChatGPT'), (3, 'Others')], db_index=True, default=1, help_text='LLM model provider choice used for generation (Gemini 2.5 Flash, ChatGPT, Others).')),
                ('raw_response', models.TextField(blank=True, help_text='Raw JSON output string returned by the LLM API.', null=True)),
                ('suggested_rule_data', models.JSONField(blank=True, default=dict, help_text='Structured JSON dictionary for rule generation requests (rule_code, rule_name, field_name, severity, strategy_key, parameters).', null=True)),
                ('status', models.IntegerField(choices=[(1, 'Pending Review'), (2, 'Accepted'), (3, 'Rejected'), (4, 'Edited')], db_index=True, default=1, help_text='Human reviewer status of the AI suggestion (Pending Review, Accepted, Rejected, Edited).')),
                ('edited_value', models.CharField(blank=True, help_text='Manual value entered by Reviewer when editing the AI recommendation.', max_length=255, null=True)),
                ('reviewer_comment', models.TextField(blank=True, help_text='Feedback or commentary provided by the Reviewer during decision.', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Timestamp when the Reviewer made a decision on this recommendation.', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User account that requested or triggered this AI recommendation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ai_recommendations', to=settings.AUTH_USER_MODEL)),
                ('exception', models.ForeignKey(blank=True, help_text='Associated loan exception analyzed by the AI copilot.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to='app.loanexception')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Reviewer user who acted upon this AI recommendation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ai_recommendations', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(blank=True, help_text='Associated validation rule generated, referenced, or affected by this recommendation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_recommendations', to='app.validationrule')),
            ],
            options={
                'verbose_name': 'AI Recommendation',
                'verbose_name_plural': 'AI Recommendations',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAIRecommendation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('recommendation_type', models.IntegerField(choices=[(1, 'Exception Review'), (2, 'Rule Generation')], db_index=True, default=1, help_text='Categorical type of AI suggestion (Exception Review or Rule Generation).')),
                ('suggested_value', models.CharField(blank=True, help_text='Suggested corrected value or proposed rule code generated by AI.', max_length=255, null=True)),
                ('explanation', models.TextField(help_text='Natural language explanation of validation failure, conflict analysis, or rule rationale.')),
                ('reasoning', models.TextField(blank=True, help_text='Step-by-step logic used by the AI copilot during decision generation.', null=True)),
                ('confidence_score', models.FloatField(default=0.0, help_text='Confidence score between 0.0 and 1.0 assigned by the AI copilot.')),
                ('prompt_text', models.TextField(blank=True, help_text='Exact prompt text submitted to the LLM model for audit transparency.', null=True)),
                ('model_name', models.IntegerField(choices=[(1, 'Gemini 2.5 Flash'), (2, 'ChatGPT'), (3, 'Others')], db_index=True, default=1, help_text='LLM model provider choice used for generation (Gemini 2.5 Flash, ChatGPT, Others).')),
                ('raw_response', models.TextField(blank=True, help_text='Raw JSON output string returned by the LLM API.', null=True)),
                ('suggested_rule_data', models.JSONField(blank=True, default=dict, help_text='Structured JSON dictionary for rule generation requests (rule_code, rule_name, field_name, severity, strategy_key, parameters).', null=True)),
                ('status', models.IntegerField(choices=[(1, 'Pending Review'), (2, 'Accepted'), (3, 'Rejected'), (4, 'Edited')], db_index=True, default=1, help_text='Human reviewer status of the AI suggestion (Pending Review, Accepted, Rejected, Edited).')),
                ('edited_value', models.CharField(blank=True, help_text='Manual value entered by Reviewer when editing the AI recommendation.', max_length=255, null=True)),
                ('reviewer_comment', models.TextField(blank=True, help_text='Feedback or commentary provided by the Reviewer during decision.', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Timestamp when the Reviewer made a decision on this recommendation.', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User account that requested or triggered this AI recommendation.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('exception', models.ForeignKey(blank=True, db_constraint=False, help_text='Associated loan exception analyzed by the AI copilot.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.loanexception')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, db_constraint=False, help_text='Reviewer user who acted upon this AI recommendation.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(blank=True, db_constraint=False, help_text='Associated validation rule generated, referenced, or affected by this recommendation.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.validationrule')),
            ],
            options={
                'verbose_name': 'historical AI Recommendation',
                'verbose_name_plural': 'historical AI Recommendations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
