# Generated by Django 6.1 on 2026-08-30 04:24

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_airecommendation_historicalairecommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalVerifiedLoanRecord',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('loan_id', models.CharField(db_index=True, help_text='Unique business identifier for the loan.', max_length=100)),
                ('borrower_id', models.CharField(blank=True, db_index=True, help_text='Unique business identifier for the primary borrower.', max_length=100, null=True)),
                ('canonical_data', models.JSONField(default=dict, help_text='Cleaned, standardized, verified loan JSON data payload.')),
                ('validation_status', models.CharField(choices=[('PASSED_CLEAN', 'Passed Validation Cleanly'), ('RESOLVED_EXCEPTION', 'Resolved Exception')], db_index=True, default='PASSED_CLEAN', help_text='Categorical status of validation outcome (Passed Clean vs Resolved Exception).', max_length=50)),
                ('reviewer_decision', models.CharField(choices=[('AUTO_PASSED', 'Auto Passed (System)'), ('APPROVED', 'Approved by Reviewer'), ('EDITED', 'Manually Edited & Resolved'), ('AI_ACCEPTED', 'Accepted AI Recommendation'), ('AI_EDITED', 'Edited & Accepted AI Recommendation')], db_index=True, default='AUTO_PASSED', help_text='Decision action that brought the loan to verified status.', max_length=50)),
                ('verified_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Timestamp when the record achieved verified status.')),
                ('record_hash', models.CharField(db_index=True, help_text='SHA-256 cryptographic hash computed over canonical_data + verified_at.', max_length=64)),
                ('lineage_summary', models.JSONField(blank=True, default=dict, help_text='Detailed breakdown listing field changes, AI suggestions, and reviewer actions.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('raw_record', models.ForeignKey(blank=True, db_constraint=False, help_text='Associated raw loan record source file lineage.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.rawloanrecord')),
                ('verified_by', models.ForeignKey(blank=True, db_constraint=False, help_text='Primary reviewer who executed the final verification approval.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Verified Loan Record',
                'verbose_name_plural': 'historical Verified Loan Records',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='VerifiedLoanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('loan_id', models.CharField(db_index=True, help_text='Unique business identifier for the loan.', max_length=100)),
                ('borrower_id', models.CharField(blank=True, db_index=True, help_text='Unique business identifier for the primary borrower.', max_length=100, null=True)),
                ('canonical_data', models.JSONField(default=dict, help_text='Cleaned, standardized, verified loan JSON data payload.')),
                ('validation_status', models.CharField(choices=[('PASSED_CLEAN', 'Passed Validation Cleanly'), ('RESOLVED_EXCEPTION', 'Resolved Exception')], db_index=True, default='PASSED_CLEAN', help_text='Categorical status of validation outcome (Passed Clean vs Resolved Exception).', max_length=50)),
                ('reviewer_decision', models.CharField(choices=[('AUTO_PASSED', 'Auto Passed (System)'), ('APPROVED', 'Approved by Reviewer'), ('EDITED', 'Manually Edited & Resolved'), ('AI_ACCEPTED', 'Accepted AI Recommendation'), ('AI_EDITED', 'Edited & Accepted AI Recommendation')], db_index=True, default='AUTO_PASSED', help_text='Decision action that brought the loan to verified status.', max_length=50)),
                ('verified_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Timestamp when the record achieved verified status.')),
                ('record_hash', models.CharField(db_index=True, help_text='SHA-256 cryptographic hash computed over canonical_data + verified_at.', max_length=64)),
                ('lineage_summary', models.JSONField(blank=True, default=dict, help_text='Detailed breakdown listing field changes, AI suggestions, and reviewer actions.')),
                ('ai_recommendations_used', models.ManyToManyField(blank=True, help_text='All AI recommendations accepted or edited during verification.', related_name='verified_records', to='app.airecommendation')),
                ('exceptions_resolved', models.ManyToManyField(blank=True, help_text='All validation exceptions flagged and resolved for this loan.', related_name='verified_records', to='app.loanexception')),
                ('participating_reviewers', models.ManyToManyField(blank=True, help_text='All human reviewers who interacted with exceptions for this loan.', related_name='participated_verified_records', to=settings.AUTH_USER_MODEL)),
                ('raw_record', models.OneToOneField(help_text='Associated raw loan record source file lineage.', on_delete=django.db.models.deletion.CASCADE, related_name='verified_record', to='app.rawloanrecord')),
                ('verified_by', models.ForeignKey(blank=True, help_text='Primary reviewer who executed the final verification approval.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verified Loan Record',
                'verbose_name_plural': 'Verified Loan Records',
                'ordering': ['-verified_at', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted__isnull', True)), fields=('loan_id',), name='unique_active_verified_loan_id')],
            },
        ),
    ]
