"""
Module D: AI Review Assistant Models for LoanGuard AI.

This module defines database models for:
1. AIRecommendation: Single unified model for all LLM copilot suggestions and rule generations,
   capturing explanations, suggested values, confidence scores, prompt/response history, LLM model choice,
   linkages to LoanException and ValidationRule models, and human reviewer audit states (Pending, Accepted, Rejected, Edited).
"""

from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _

from app.models.base import BaseModel
from app.models.validation import LoanException, ValidationRule


class AIRecommendation(BaseModel):
    """
    Unified AI copilot recommendation model for exception reviews and natural language rule generations.

    Captures LLM explanation, suggested numeric or structural corrections, generated rule payloads,
    confidence scores, full prompt/response history, LLM model provider, and reviewer override status
    enforcing Section 9 human-in-the-loop audit controls.
    Inherits soft-deletion, timestamps, and history from BaseModel.
    """

    class RecommendationType(models.IntegerChoices):
        EXCEPTION_REVIEW = 1, _("Exception Review")
        RULE_GENERATION = 2, _("Rule Generation")

    class RecommendationStatus(models.IntegerChoices):
        PENDING = 1, _("Pending Review")
        ACCEPTED = 2, _("Accepted")
        REJECTED = 3, _("Rejected")
        EDITED = 4, _("Edited")

    class ModelProvider(models.IntegerChoices):
        GEMINI = 1, _("Gemini")
        CHATGPT = 2, _("ChatGPT")
        OTHERS = 3, _("Others")
        OPENCODE_ZEN = 4, _("OpenCode Zen")

    recommendation_type = models.IntegerField(
        choices=RecommendationType.choices,
        default=RecommendationType.EXCEPTION_REVIEW,
        db_index=True,
        help_text=_("Categorical type of AI suggestion (Exception Review or Rule Generation)."),
    )
    exception = models.ForeignKey(
        LoanException,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="ai_recommendations",
        help_text=_("Associated loan exception analyzed by the AI copilot."),
    )
    rule = models.ForeignKey(
        ValidationRule,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="ai_recommendations",
        help_text=_(
            "Associated validation rule generated, referenced, or affected by this recommendation."
        ),
    )
    suggested_value = models.CharField(
        max_length=255,
        blank=True,
        null=True,
        help_text=_("Suggested corrected value or proposed rule code generated by AI."),
    )
    explanation = models.TextField(
        help_text=_(
            "Natural language explanation of validation failure, conflict analysis, or rule rationale."
        ),
    )
    reasoning = models.TextField(
        blank=True,
        null=True,
        help_text=_("Step-by-step logic used by the AI copilot during decision generation."),
    )
    confidence_score = models.FloatField(
        default=0.0,
        help_text=_("Confidence score between 0.0 and 1.0 assigned by the AI copilot."),
    )
    prompt_text = models.TextField(
        blank=True,
        null=True,
        help_text=_("Exact prompt text submitted to the LLM model for audit transparency."),
    )
    model_name = models.IntegerField(
        choices=ModelProvider.choices,
        default=ModelProvider.OPENCODE_ZEN,
        db_index=True,
        help_text=_(
            "LLM model provider choice used for generation (Gemini, ChatGPT, OpenCode Zen, Others)."
        ),
    )
    raw_response = models.TextField(
        blank=True,
        null=True,
        help_text=_("Raw JSON output string returned by the LLM API."),
    )
    suggested_rule_data = models.JSONField(
        default=dict,
        blank=True,
        null=True,
        help_text=_(
            "Structured JSON dictionary for rule generation requests (rule_code, rule_name, field_name, severity, strategy_key, parameters)."
        ),
    )
    status = models.IntegerField(
        choices=RecommendationStatus.choices,
        default=RecommendationStatus.PENDING,
        db_index=True,
        help_text=_(
            "Human reviewer status of the AI suggestion (Pending Review, Accepted, Rejected, Edited)."
        ),
    )
    edited_value = models.CharField(
        max_length=255,
        blank=True,
        null=True,
        help_text=_("Manual value entered by Reviewer when editing the AI recommendation."),
    )
    reviewer_comment = models.TextField(
        blank=True,
        null=True,
        help_text=_("Feedback or commentary provided by the Reviewer during decision."),
    )
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="created_ai_recommendations",
        help_text=_("User account that requested or triggered this AI recommendation."),
    )
    reviewed_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="reviewed_ai_recommendations",
        help_text=_("Reviewer user who acted upon this AI recommendation."),
    )
    reviewed_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text=_("Timestamp when the Reviewer made a decision on this recommendation."),
    )

    class Meta:
        verbose_name = _("AI Recommendation")
        verbose_name_plural = _("AI Recommendations")
        ordering = ["-created"]

    def __str__(self) -> str:
        target_str = (
            f"Exception #{self.exception_id}"
            if self.exception_id
            else (f"Rule #{self.rule_id}" if self.rule_id else f"Rec #{self.id}")
        )
        return f"AI Rec [{self.get_recommendation_type_display()}] for {target_str} ({self.get_status_display()})"

    @property
    def is_pending(self) -> bool:
        """Returns True if the recommendation is pending reviewer action."""
        return self.status == self.RecommendationStatus.PENDING

    @property
    def is_accepted(self) -> bool:
        """Returns True if the reviewer accepted the recommendation."""
        return self.status == self.RecommendationStatus.ACCEPTED

    @property
    def is_rejected(self) -> bool:
        """Returns True if the reviewer rejected the recommendation."""
        return self.status == self.RecommendationStatus.REJECTED

    @property
    def is_edited(self) -> bool:
        """Returns True if the reviewer edited and accepted the recommendation."""
        return self.status == self.RecommendationStatus.EDITED

    @property
    def confidence_percentage(self) -> str:
        """Returns the confidence score formatted as a percentage string (e.g., '85.0%')."""
        return f"{(self.confidence_score or 0.0) * 100:.1f}%"
