"""
Module C: Reviewer Workspace & Exception Queue View for LoanGuard AI.

Provides exception management dashboard strictly for Reviewer role.
Lists LoanExceptions with filtering, search, severity badges, and AI recommendation controls.
"""

from typing import Any

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.db.models import QuerySet
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.views.generic import ListView

from app.domain.roles import AppPermission
from app.filters import LoanExceptionFilter
from app.mixins import AnyPermissionRequiredMixin
from app.models import LoanException, ValidationSeverity


class ReviewerDashboardView(LoginRequiredMixin, AnyPermissionRequiredMixin, ListView):
    """
    Class-Based View for Reviewer Workspace and Exception Queue.

    Restricted strictly to users with REVIEWER_CAN_INSPECT_EXCEPTIONS permission.
    Lists all LoanExceptions generated by the Validation Engine using LoanExceptionFilter.
    Supports HTMX partial rendering for real-time filter, search, and pagination updates.
    """

    model = LoanException
    template_name = "dashboard/reviewer/index.html"
    context_object_name = "exceptions"
    paginate_by = 25
    permissions_required = [AppPermission.REVIEWER_CAN_INSPECT_EXCEPTIONS]

    def dispatch(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        user = request.user
        if not user.is_authenticated:
            return self.handle_no_permission()

        # Enforce strict Role Permission Check for Reviewer
        if not (
            user.is_superuser
            or user.is_reviewer
            or user.has_category_perm(AppPermission.REVIEWER_CAN_INSPECT_EXCEPTIONS)
        ):
            raise PermissionDenied(
                "Access Denied: Only Reviewers can access the Exception Queue workspace."
            )
        return super().dispatch(request, *args, **kwargs)

    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        self.object_list = self.get_queryset()
        context = self.get_context_data()
        if request.headers.get("HX-Request") == "true":
            return render(request, "dashboard/reviewer/includes/exceptions_container.html", context)
        return self.render_to_response(context)

    def get_queryset(self) -> QuerySet[LoanException]:
        base_qs = LoanException.objects.select_related(
            "batch", "raw_record", "rule", "resolved_by"
        ).order_by("-severity", "-created")

        self.filterset = LoanExceptionFilter(self.request.GET, queryset=base_qs)
        return self.filterset.qs

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        all_exceptions = LoanException.objects.all()

        context["filter"] = getattr(self, "filterset", None)
        context["total_exceptions"] = all_exceptions.count()
        context["open_exceptions"] = all_exceptions.filter(
            status=LoanException.ExceptionStatus.OPEN
        ).count()
        context["under_review_exceptions"] = all_exceptions.filter(
            status=LoanException.ExceptionStatus.UNDER_REVIEW
        ).count()
        context["resolved_exceptions"] = all_exceptions.filter(
            status__in=[
                LoanException.ExceptionStatus.RESOLVED_ACCEPTED,
                LoanException.ExceptionStatus.RESOLVED_EDITED,
            ]
        ).count()
        context["rejected_exceptions"] = all_exceptions.filter(
            status=LoanException.ExceptionStatus.REJECTED
        ).count()

        # Severity breakdown metrics
        context["critical_count"] = all_exceptions.filter(
            severity=ValidationSeverity.CRITICAL
        ).count()
        context["high_count"] = all_exceptions.filter(severity=ValidationSeverity.HIGH).count()
        context["medium_count"] = all_exceptions.filter(severity=ValidationSeverity.MEDIUM).count()
        context["low_count"] = all_exceptions.filter(severity=ValidationSeverity.LOW).count()

        context["severity_choices"] = ValidationSeverity.choices
        context["status_choices"] = LoanException.ExceptionStatus.choices
        context["current_severity"] = self.request.GET.get("severity", "")
        context["current_status"] = self.request.GET.get("status", "")
        context["search_query"] = self.request.GET.get("q", "")
        context["title"] = "Reviewer Workspace - Loan Exception Queue"
        return context
